%YAML 1.1
---
name: Process Nim
on:
  push:
    branches: [master]
    paths:
    - .github/workflows/**
    - '*.nimble'
    - '**.nim'
    - '**.nims'
    - '**nim.cfg'
    - '**nimdoc.cfg'
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: nim
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  nim:
    strategy:
      matrix:
        nim-version:
          # - 0.19.x # `choosenim` compiled with Nim 1.6.14 fails mysteriously on it.
          - 0.20.x
          - 1.0.x
          - 1.2.x
          - 1.4.x
          - 1.6.x
    name: Test on ${{ matrix.nim-version }}
    runs-on: ubuntu-latest

    steps:
    - name: Cache Nim toolchain
      id: nim-cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-Nim-${{ matrix.nim-version }}
        path: |-
          ~/.choosenim/toolchains/
          ~/.choosenim/current
          ~/.nimble/bin/

    - name: Set up Nim toolchain
      if: steps.nim-cache.outputs.cache-hit != 'true'
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Adjust PATH
      run: echo ~/.nimble/bin >> "$GITHUB_PATH"

    - name: Check out the project
      uses: actions/checkout@v3

    - name: Run tests
      run: |-
        if [[ ${{ matrix.nim-version }} < 1.4 ]]; then
          flags=()
        else
          flags=(--hint=MsgOrigin:off)
        fi
        nimble -y --verbose test --verbosity=2 --hint=GlobalVar:off "${flags[@]}"

    - name: Generate API docs
      if: matrix.nim-version == '1.6.x'
      run: >-
        nimble doc letUtils.nim
        --git.url="${{ github.server_url }}/${{ github.repository }}"
        --git.commit="${{ github.ref_name }}"

    - name: Set up Pages
      if: matrix.nim-version == '1.6.x'
      uses: actions/configure-pages@v3

    - name: Upload API docs
      if: matrix.nim-version == '1.6.x'
      uses: actions/upload-pages-artifact@v1
      with:
        path: htmldocs/

  deploy-pages:
    name: Deploy Pages
    needs: nim
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Pages
      id: deployment
      uses: actions/deploy-pages@v1
